# Example
# https://github.com/grpc-ecosystem/grpc-gateway/blob/main/examples/internal/proto/examplepb/unannotated_echo_service.swagger.yaml#L4
openapiOptions:
  file:
    - file: "user.proto"
      option:
        info:
          title: User APIs
          version: "1.0"
